/**
 * Post-OpenNext split-build.
 *
 * Why this exists: a single Cloudflare Worker that bundles middleware
 * + 9.2 MB of server code is pushing the cold-start CPU budget far
 * enough to surface Error 1102 intermittently on bo.termimal.com.
 * Splitting into two workers (lightweight middleware + heavy server)
 * means most requests (cached, redirects, asset routes) never spin up
 * the server isolate at all. opennextjs/cloudflare already ships the
 * pieces separately — `.open-next/middleware/handler.mjs` (590 KB)
 * and `.open-next/server-functions/default/handler.mjs` (9.2 MB) —
 * but glues them together via dynamic import in
 * `.open-next/worker.js`. This script generates two NEW entrypoints
 * that wire them via service binding instead.
 *
 * Output:
 *   .open-next/worker.middleware.js  — uploaded as the `termimal-admin` worker (bo.termimal.com)
 *   .open-next/worker.server.js      — uploaded as the `termimal-admin-server` worker (no public route)
 *
 * Run AFTER `opennextjs-cloudflare build` and BEFORE `wrangler deploy`.
 * Idempotent — re-running with the same .open-next/ produces identical
 * outputs.
 */
const fs   = require("node:fs");
const path = require("node:path");

const ROOT     = path.resolve(__dirname, "..");
const OPEN_OUT = path.join(ROOT, ".open-next");
const MID_PATH = path.join(OPEN_OUT, "worker.middleware.js");
const SRV_PATH = path.join(OPEN_OUT, "worker.server.js");

if (!fs.existsSync(OPEN_OUT)) {
  console.error(`[build-split] no .open-next directory at ${OPEN_OUT} — run opennextjs-cloudflare build first.`);
  process.exit(1);
}

// ────────────────────────────────────────────────────────────────────
// 1) Middleware worker entrypoint.
//
// Identical to OpenNext's worker.js except line ~38 — instead of
// dynamically importing the server bundle, we forward the modified
// request to the SERVER service binding. This is the cold-start CPU
// win: when the middleware can serve a request itself (cache hit,
// redirect, image route, skew protection), we never pull in the 9.2 MB
// server module at all.
// ────────────────────────────────────────────────────────────────────

const middlewareEntry = `// AUTO-GENERATED by scripts/build-split.cjs — do not edit.
//
// Termimal admin — MIDDLEWARE worker entrypoint.
// Pairs with .open-next/worker.server.js (deployed as termimal-admin-server)
// via the SERVER service binding configured in wrangler.middleware.jsonc.
//
// For most requests (cache hits, redirects, asset routes, image
// transforms, skew protection) this worker answers entirely on its
// own. Only requests that need server-side rendering or API route
// execution are forwarded to the server worker via env.SERVER.fetch.

import { handleCdnCgiImageRequest, handleImageRequest } from "./cloudflare/images.js";
import { runWithCloudflareRequestContext } from "./cloudflare/init.js";
import { maybeGetSkewProtectionResponse } from "./cloudflare/skew-protection.js";
import { handler as middlewareHandler } from "./middleware/handler.mjs";

// Durable Objects live on the MIDDLEWARE worker so middleware-side
// cache + queue + purge logic can talk to them directly. The server
// worker accesses the SAME instances via script_name = "termimal-admin"
// bindings (see wrangler.server.jsonc).
export { DOQueueHandler }      from "./.build/durable-objects/queue.js";
export { DOShardedTagCache }   from "./.build/durable-objects/sharded-tag-cache.js";
export { BucketCachePurge }    from "./.build/durable-objects/bucket-cache-purge.js";

export default {
  async fetch(request, env, ctx) {
    return runWithCloudflareRequestContext(request, env, ctx, async () => {
      const skew = maybeGetSkewProtectionResponse(request);
      if (skew) return skew;

      const url = new URL(request.url);

      // Cloudflare image transforms in dev.
      if (url.pathname.startsWith("/cdn-cgi/image/")) {
        return handleCdnCgiImageRequest(url, env);
      }
      // Next default image loader fallback.
      if (url.pathname ===
          \`\${globalThis.__NEXT_BASE_PATH__}/_next/image\${globalThis.__TRAILING_SLASH__ ? "/" : ""}\`) {
        return await handleImageRequest(url, request.headers, env);
      }

      // Run middleware — may return a Response (early-exit cache hit,
      // redirect, etc.) or a Request to forward to the server.
      const reqOrResp = await middlewareHandler(request, env, ctx);
      if (reqOrResp instanceof Response) return reqOrResp;

      // Forward to server worker via service binding. The server worker
      // is bound as env.SERVER in wrangler.middleware.jsonc.
      if (!env.SERVER || typeof env.SERVER.fetch !== "function") {
        // Misconfiguration — server binding not present. Return a
        // descriptive 500 so the operator sees the cause in CF logs
        // rather than a generic Worker exception.
        return new Response("middleware: SERVER service binding is missing — check wrangler.middleware.jsonc", {
          status: 500,
        });
      }
      return env.SERVER.fetch(reqOrResp);
    });
  },
};
`;

// ────────────────────────────────────────────────────────────────────
// 2) Server worker entrypoint.
//
// Tiny wrapper around the OpenNext server bundle. Receives requests
// from the middleware worker via service binding. Only this worker
// ever loads the 9.2 MB handler.mjs into a V8 isolate — and only when
// the middleware decided it actually needs server-side rendering.
// ────────────────────────────────────────────────────────────────────

const serverEntry = `// AUTO-GENERATED by scripts/build-split.cjs — do not edit.
//
// Termimal admin — SERVER worker entrypoint.
// Receives requests from termimal-admin (middleware worker) via the
// SERVER service binding. Runs Next.js SSR + API routes.

import { runWithCloudflareRequestContext } from "./cloudflare/init.js";
import { handler } from "./server-functions/default/handler.mjs";

export default {
  async fetch(request, env, ctx) {
    return runWithCloudflareRequestContext(request, env, ctx, async () => {
      return handler(request, env, ctx, request.signal);
    });
  },
};
`;

fs.writeFileSync(MID_PATH, middlewareEntry);
fs.writeFileSync(SRV_PATH, serverEntry);

console.log(`[build-split] wrote ${path.relative(ROOT, MID_PATH)} (${middlewareEntry.length} bytes)`);
console.log(`[build-split] wrote ${path.relative(ROOT, SRV_PATH)} (${serverEntry.length} bytes)`);
